# Using version 3 to provide play-with-docker badge
# You can change to version 2 without breaking.
#version: '2'
version: '3'
services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_USER=hackmd
      - MYSQL_PASSWORD=hackmdpass
      - MYSQL_DATABASE=hackmd
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - /home/deepcompute/docker-hackmd/online_data:/var/lib/mysql
      - ./resources/utf8.cnf:/etc/mysql/conf.d/utf8.cnf
    restart: always

  app:
    # TODO need to remove below comment with proper name
    # image: <image that is built>
    #mem_limit: 256mb         # version 2 only
    #memswap_limit: 512mb     # version 2 only
    #read_only: true          # not supported in swarm mode, enable along with tmpfs
    #tmpfs:
    #  - /tmp:size=512K
    #  - /hackmd/tmp:size=1M
    #  # Make sure you remove this when you use filesystem as upload type
    #  - /hackmd/public/uploads:size=10M
    environment:
      - HMD_DB_URL=mysql://hackmd:hackmdpass@database:3306/hackmd
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_DEFAULT_PERMISSION=limited
      - CMD_ALLOW_EMAIL_REGISTER=false
      - CMD_GOOGLE_CLIENTID=xxxxxxxxxxxxxxxxxxxxxxxxxx
      - CMD_GOOGLE_CLIENTSECRET=xxxxxxxxxxxxxxxxxxxx
      - CMD_GOOGLE_ALLOWEDDOMAINS=deepcompute.com,nudjur.com
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - database
    volumes:
      - /home/deepcompute/docker-hackmd/online_uploads:/home/hackmd/app/public/uploads
      - /home/deepcompute/docker-hackmd/resources/config.json:/files/config.json
