# Using version 3 to provide play-with-docker badge
# You can change to version 2 without breaking.
#version: '2'
version: '3'
services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /home/deepcompute/docker-hackmd/online_data:/var/lib/mysql
      - ./resources/utf8.cnf:/etc/mysql/conf.d/utf8.cnf
      # Uncomment the below line to enable general logging
      # - ./resources/general_logging.cnf:/etc/mysql/conf.d/general_logging.cnf
    ports:
      - 3307:3306
    restart: always

  app:
    image: jaswanth098/codimd:1.5.0
    #mem_limit: 256mb         # version 2 only
    #memswap_limit: 512mb     # version 2 only
    #read_only: true          # not supported in swarm mode, enable along with tmpfs
    #tmpfs:
    #  - /tmp:size=512K
    #  - /hackmd/tmp:size=1M
    #  # Make sure you remove this when you use filesystem as upload type
    #  - /hackmd/public/uploads:size=10M
    environment:
      - HMD_DB_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}
      - HMD_PROTOCOL_USESSL=true
      - HMD_DOMAIN=${HMD_DOMAIN}
      - HMD_URL_ADDPORT=false
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_DEFAULT_PERMISSION=limited
      - CMD_ALLOW_EMAIL_REGISTER=false
      - CMD_GOOGLE_CLIENTID=${CMD_GOOGLE_CLIENTID}
      - CMD_GOOGLE_CLIENTSECRET=${CMD_GOOGLE_CLIENTSECRET}
      - CMD_GOOGLE_ALLOWEDDOMAINS=${CMD_GOOGLE_ALLOWEDDOMAINS}
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - database
    volumes:
      - /home/deepcompute/docker-hackmd/online_uploads:/home/hackmd/app/public/uploads
      - /home/deepcompute/docker-hackmd/resources/config.json:/files/config.json
